/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OrderAndReservation;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;

/**
 *
 * @author zubaeyr
 */
public class OrderingSystem extends javax.swing.JPanel {

    /**
     * Creates new form OrderingSystem
     */
    Statement statement;
    String sql;
    ResultSet result;
    String[] categories;
    EmptyView empty=new EmptyView();
    CartPanel cart;
    JFrame f;
    public OrderingSystem(Statement statement) {
        this.statement=statement;
               f=new JFrame();
        cart=new CartPanel(statement,f);
        UpdateCategories(); //Updates the CategoryComboBox with category names
       initComponents();

         f.setLayout(new BorderLayout());
        f.add(cart);
         f.setLocation(150, 100);
        f.setUndecorated(true);
        f.pack();
        f.setResizable(false);
        f.setResizable(true);
        f.revalidate();
	try{
 	       f.setOpacity((float) 0.96);
    	}catch(Exception e){}
         
    }
    
    //Updates the CategoryComboBox with category names
     public void UpdateCategories(){
            String sql="Select CName from MealCategory;";
        try{
            result=statement.executeQuery(sql);
            result.last();
            int items=result.getRow();
            categories=new String[items+1];
            categories[0]="All";
            result.first();
            for(int i=1;i<=items;i++){
                categories[i]=result.getString("CName");
                
                result.next();
            }
            
        }   catch(Exception e){
            System.out.println("Break point 1: mealitemsmaintenance");
        }
     
    }
     
     public void UpdateDisplayPanel(String sql){   
        DisplayPanel.removeAll();
        int no_of_meals=0,no_of_gridrows=0;
        try {
            result=statement.executeQuery(sql);
            result.last();
            no_of_meals=result.getRow();
            no_of_gridrows=no_of_meals/3;
            result.first();
        } catch (SQLException ex) {
            System.out.println("Break-Point 2: Mealitems Maintenance");
        }
        if(no_of_meals%3!=0){
            no_of_gridrows++;
        }
        if(no_of_meals<9){
            no_of_gridrows=3;
        }
        DisplayPanel.setLayout(new GridLayout(no_of_gridrows,3));      
        for(int i=0;i<no_of_meals;i++)
        {
            try {
                Items itm=new Items(result.getString("MImage"),result.getString("MName"),DetailsPanel,statement,empty,cart);
                DisplayPanel.add(itm);
                itm.orderingpan=this;
                result.next();
         
            } catch (SQLException ex) {
                System.out.println("Break-Point 3: Mealitems Maintenance");
            }
        }
        for(int i=0;i<((no_of_gridrows*3)-(no_of_meals));i++){
            DisplayPanel.add(new Items("black.png","",DetailsPanel,statement,empty,cart));
        }
        DisplayPanel.revalidate();
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SearchPanel = new javax.swing.JPanel();
        CategoryComboBox = new javax.swing.JComboBox();
        ViewMealsButton = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        SearchField = new javax.swing.JTextField();
        Label2 = new javax.swing.JLabel();
        ViewCartButton = new javax.swing.JLabel();
        DetailsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ScrollPane = new javax.swing.JScrollPane();
        DisplayPanel = new javax.swing.JPanel();

        setOpaque(false);

        SearchPanel.setBackground(new java.awt.Color(77, 72, 72));

        CategoryComboBox.setBackground(new java.awt.Color(124, 115, 115));
        CategoryComboBox.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        CategoryComboBox.setForeground(new java.awt.Color(246, 238, 238));
        CategoryComboBox.setMaximumRowCount(4);
        CategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(categories));
        CategoryComboBox.setBorder(null);

        ViewMealsButton.setBackground(new java.awt.Color(118, 116, 116));
        ViewMealsButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        ViewMealsButton.setForeground(new java.awt.Color(254, 254, 254));
        ViewMealsButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewMealsButton.setText("View Meals");
        ViewMealsButton.setBorder(null);
        ViewMealsButton.setOpaque(true);
        ViewMealsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewMealsButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewMealsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewMealsButtonMouseExited(evt);
            }
        });

        Label1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Label1.setForeground(new java.awt.Color(232, 227, 227));
        Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label1.setText("Category");

        SearchField.setBackground(new java.awt.Color(40, 40, 40));
        SearchField.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        SearchField.setForeground(new java.awt.Color(254, 254, 254));
        SearchField.setBorder(null);
        SearchField.setCaretColor(new java.awt.Color(253, 251, 251));
        SearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchFieldKeyReleased(evt);
            }
        });

        Label2.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        Label2.setForeground(new java.awt.Color(232, 227, 227));
        Label2.setText("Search Meal");

        ViewCartButton.setBackground(new java.awt.Color(118, 116, 116));
        ViewCartButton.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        ViewCartButton.setForeground(new java.awt.Color(254, 254, 254));
        ViewCartButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewCartButton.setText("View Cart");
        ViewCartButton.setBorder(null);
        ViewCartButton.setOpaque(true);
        ViewCartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewCartButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewCartButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewCartButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchPanelLayout.createSequentialGroup()
                        .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ViewMealsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(306, 306, 306)
                .addComponent(ViewCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewMealsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ViewCartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        DetailsPanel.setBackground(new java.awt.Color(73, 73, 73));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(197, 197, 197));
        jLabel1.setText("Click on the Meal Item which you want");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(197, 197, 197));
        jLabel2.setText("to Edit, Delte or View Details");

        javax.swing.GroupLayout DetailsPanelLayout = new javax.swing.GroupLayout(DetailsPanel);
        DetailsPanel.setLayout(DetailsPanelLayout);
        DetailsPanelLayout.setHorizontalGroup(
            DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        DetailsPanelLayout.setVerticalGroup(
            DetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetailsPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );

        ScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        DisplayPanel.setBackground(new java.awt.Color(12, 2, 2));
        DisplayPanel.setAutoscrolls(true);

        javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
        DisplayPanel.setLayout(DisplayPanelLayout);
        DisplayPanelLayout.setHorizontalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
        );
        DisplayPanelLayout.setVerticalGroup(
            DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        ScrollPane.setViewportView(DisplayPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane)
                    .addComponent(DetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ViewMealsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewMealsButtonMouseClicked
        // TODO add your handling code here:

        String CName=CategoryComboBox.getSelectedItem().toString();
        if(CName.equals("All")){
            sql="select * from Meals;";
        }
        else{
            sql="select * from Meals where CName='"+CName+"';";
        }
        UpdateDisplayPanel(sql);
    }//GEN-LAST:event_ViewMealsButtonMouseClicked

    private void ViewMealsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewMealsButtonMouseEntered
        // TODO add your handling code here:
        ViewMealsButton.setBackground(new java.awt.Color(235, 228, 228));
        ViewMealsButton.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_ViewMealsButtonMouseEntered

    private void ViewMealsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewMealsButtonMouseExited
        // TODO add your handling code here:
        ViewMealsButton.setBackground(new java.awt.Color(118, 116, 116));
        ViewMealsButton.setForeground(new java.awt.Color(254, 254, 254));
    }//GEN-LAST:event_ViewMealsButtonMouseExited

    private void SearchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchFieldKeyReleased
        // TODO add your handling code here:
        String searchString=SearchField.getText().trim();
        String CName=CategoryComboBox.getSelectedItem().toString();
        if(CName.equals("All")){
            sql="select * from Meals where MName LIKE '%"+searchString+"%';";
        }
        else{
            sql="select * from Meals where MName LIKE '%"+searchString+"%' AND CName='"+CName+"';";
        }
        UpdateDisplayPanel(sql);
    }//GEN-LAST:event_SearchFieldKeyReleased

    private void ViewCartButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewCartButtonMouseClicked
        // TODO add your handling code here:
        f.setVisible(true);  
        cart.showPanel();
      
    }//GEN-LAST:event_ViewCartButtonMouseClicked

    private void ViewCartButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewCartButtonMouseEntered
        // TODO add your handling code here:
        ViewCartButton.setBackground(new java.awt.Color(235, 228, 228));
        ViewCartButton.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_ViewCartButtonMouseEntered

    private void ViewCartButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewCartButtonMouseExited
        // TODO add your handling code here:
          ViewCartButton.setBackground(new java.awt.Color(118, 116, 116));
        ViewCartButton.setForeground(new java.awt.Color(254, 254, 254));
    }//GEN-LAST:event_ViewCartButtonMouseExited

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CategoryComboBox;
    private javax.swing.JPanel DetailsPanel;
    private javax.swing.JPanel DisplayPanel;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JTextField SearchField;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JLabel ViewCartButton;
    private javax.swing.JLabel ViewMealsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
