/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package OrderAndReservation;

import java.awt.Color;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
//import practice.*;

/**
 *
 * @author student
 */
public class Table extends javax.swing.JPanel {

    /**
     * Creates new form Table
     */
    Connection con;
    Statement s,stmt;
    ResultSet r,rs;
    String sql;
    Color color;
    String tableNo,status;
    int size,flag=0;
    JFrame reservationForm;
    String Ip;
    public Table(String tableNo,String status,int size,String Ip) {  
        this.Ip=Ip;
        this.tableNo=tableNo;
        this.status=status;
        this.size=size;
        getConnection();
        initComponents();
        setColor();
    }
    private void getConnection() {
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                System.out.println("Sorry, Driver Class is not found");
            }
            System.out.println("Successfully loaded driver.....");
            con=DriverManager.getConnection("jdbc:mysql://"+Ip+":3306/LosPollosHermanos","root","8154219449");
            System.out.println("Connecting to the database.....");
            stmt=con.createStatement();
            s=con.createStatement();
            System.out.println("Successfully created connection.....!!");
        } catch (SQLException ex) {
            System.out.println("Error in getting the Connection");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(8, 246, 6));
        setPreferredSize(new java.awt.Dimension(100, 100));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(8, 254, 14));
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(tableNo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if(flag==0)
        {
            if(JOptionPane.showConfirmDialog(null, new JLabel("Do you want to reserve this table ? "),"Select an Option",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
            {
               reservationForm=new JFrame("Reservation Form");
               reservationForm.setSize(400, 300);
               reservationForm.setUndecorated(true);
               reservationForm.setContentPane(new Reservation(tableNo, this,reservationForm,Ip));
               reservationForm.setVisible(true);
               reservationForm.setLocationRelativeTo(null);
               reservationForm.setOpacity(0.90f);
            }
        }
        else if(flag==1)
        {
            try {
                sql="select Status from Tables where TableNo='"+tableNo+"';";
                rs=stmt.executeQuery(sql);                
                if(rs.next()){status=rs.getString("Status");}
                JPanel j=new JPanel();
                JLabel jt=null;
                if(status.equals("occupied1")){
                    jt=new JLabel("Service Status : Un-served ");
                }
                if(status.equals("occupied2")){
                    jt=new JLabel("Service Status : Served ");
                }
                j.setLayout(new javax.swing.BoxLayout(j,BoxLayout.Y_AXIS));
                j.add(jt);
                j.add(new JLabel("  "));
                j.add(new JLabel("Do you want to Unreserve this table ? "));
                
                if(JOptionPane.showConfirmDialog(null, j,"Select an Option",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
                {
                    sql="update Tables set Status='unoccupied' where TableNo='"+tableNo+"';";
                    stmt.executeUpdate(sql);
                }
                
            } catch (SQLException ex) {
                System.out.println("Problem in getting the cook status....");
                ex.printStackTrace();
            }
        }
        else
        {
            if(JOptionPane.showConfirmDialog(null,new JLabel("Do you want to unreserve this table ?"),"Select an Option",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
                {
                try {
                    sql="update Tables set Status='unoccupied' where TableNo='"+tableNo+"';";
                    stmt.executeUpdate(sql);
                    sql="delete from Reservation where ResTableNo='"+tableNo+"' and ResSTime<=curtime() and ResETime>curtime();";
                    stmt.executeUpdate(sql);
                } catch (SQLException ex) {
                    System.out.println("Problem in unreserving the reserved table.");
                    ex.printStackTrace();
                }
                }
        }
    }//GEN-LAST:event_formMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:        
        setBackground(Color.gray);
        jLabel1.setForeground(Color.white);
        setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        setBackground(color);
        jLabel1.setForeground(Color.black); 
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_formMouseExited
    private void setColor() {
        if(status.equalsIgnoreCase("unoccupied"))
        {            
            color=Color.green;
            setToolTipText("Unoccupied"+"(Size: "+size+")");
            jLabel1.setForeground(Color.black);
        }
        else if(status.startsWith("occupied"))
        {
            flag=1;
            color=Color.red;
            setToolTipText("Occupied"+"(Size: "+size+")");
            jLabel1.setForeground(Color.white);
        }
        else
        {
            flag=2;
            color=Color.yellow;
            setToolTipText("reserved"+"(Size: "+size+")");
            jLabel1.setForeground(Color.black);
            
        }
        setBackground(color);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
