/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package chef;

//import javaapplication1.*;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author student
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    CardLayout card;
    Connection con;  
    Statement s,stmt;
    ResultSet r,rs;
    String sql;
    JFrame loginframe;
    String dTime,receiverName,memberId,phoneNo,address=null,orderNo,Ip;
    public MainFrame(String FullName, String Ip, JFrame loginframe) {
        this.Ip=Ip;
        this.loginframe=loginframe;
        //Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        card=new CardLayout();
        initComponents();
        getConnection();
        setSize(1280,770);
        setLocationRelativeTo(null);
        setLocation(this.getX(),0);
        //getContentPane().setBackground(Color.green);
       // setFullScreen();
     
        //setResizable(false);
	try{
        setOpacity(0.93f);
	}catch(Exception e){}
        setVisible(true);
        start();
        jLabel12.setText("Welcome "+FullName);
    }
    public void getDetails()
    {
        try {
            sql="select Receiver,CPhoneNo,DAddress,DTime from Delivery where OrderNo='"+orderNo+"';";
            rs=stmt.executeQuery(sql);
            if(rs.next()){
            receiverLabel.setText("Receiver : "+rs.getString("Receiver"));
            phoneNoLabel.setText("Phone : "+rs.getString("CPhoneNo"));
            address=rs.getString("DAddress");
            dTimeLabel.setText("DTime : "+rs.getString("DTime"));
            sql="select MemberID from Orders where OrderNo='"+orderNo+"';";
            rs=stmt.executeQuery(sql);
            rs.next();
            memberIdLabel.setText("Member ID : "+rs.getString("MemberID"));
            if(address==null)
            {addressLabel.setText("Delivery Address : "+"Collect Myself");
            }
            else{addressLabel.setText("Address : "+address);}
            }
            else
            {
                addressLabel.setText("Delivery information of this order has not been found.");
            }
        } catch (SQLException ex) {
            System.out.println("Failed in getting delivery Details....");
            ex.printStackTrace();
        } 
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderDetailsPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        searchOrderTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        receiverLabel = new javax.swing.JLabel();
        phoneNoLabel = new javax.swing.JLabel();
        dTimeLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        clearAllButton = new javax.swing.JButton();
        memberIdLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(2, 2, 2));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        orderDetailsPanel.setBackground(new java.awt.Color(1, 1, 1));
        orderDetailsPanel.setLayout(new java.awt.CardLayout());

        jPanel5.setBackground(new java.awt.Color(123, 118, 113));
        jPanel5.setPreferredSize(new java.awt.Dimension(795, 114));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 25)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 250, 250));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chef/ice-cream.png"))); // NOI18N
        jLabel11.setText("Los Pollos Hermanos");
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(254, 254, 254));
        jLabel12.setText("Welcome Mr. Kumar");

        jLabel13.setBackground(new java.awt.Color(123, 118, 113));
        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(250, 250, 250));
        jLabel13.setText(" X ");
        jLabel13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(253, 251, 251));
        jLabel14.setText("Logout");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 250, 250));
        jLabel15.setText("|");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addComponent(jLabel13)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );

        jScrollPane1.setMaximumSize(new java.awt.Dimension(600, 32767));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(440, 24));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(440, 500));

        ordersPanel.setBackground(new java.awt.Color(1, 1, 1));
        ordersPanel.setForeground(new java.awt.Color(252, 245, 245));
        ordersPanel.setMaximumSize(new java.awt.Dimension(440, 32767));
        ordersPanel.setMinimumSize(new java.awt.Dimension(440, 100));
        ordersPanel.setLayout(new javax.swing.BoxLayout(ordersPanel, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(ordersPanel);

        searchPanel.setBackground(new java.awt.Color(16, 15, 14));
        searchPanel.setForeground(new java.awt.Color(247, 237, 237));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 248, 248));
        jLabel1.setText("Enter Order No : ");

        searchButton.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        receiverLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        receiverLabel.setForeground(new java.awt.Color(253, 248, 248));

        phoneNoLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        phoneNoLabel.setForeground(new java.awt.Color(253, 248, 248));

        dTimeLabel.setBackground(new java.awt.Color(1, 1, 1));
        dTimeLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        dTimeLabel.setForeground(new java.awt.Color(253, 248, 248));

        addressLabel.setBackground(new java.awt.Color(1, 1, 1));
        addressLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(253, 248, 248));

        clearAllButton.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        clearAllButton.setText("Clear All");
        clearAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllButtonActionPerformed(evt);
            }
        });

        memberIdLabel.setBackground(new java.awt.Color(1, 1, 1));
        memberIdLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        memberIdLabel.setForeground(new java.awt.Color(248, 241, 241));

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(dTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchOrderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addComponent(receiverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(phoneNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchOrderTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(clearAllButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiverLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberIdLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .addComponent(orderDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
       // jLabel6.setForeground(Color.black);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
        //jLabel6.setForeground(new java.awt.Color(255, 250, 250));
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        System.exit(0);//just hide instead of exiting
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        jLabel13.setBackground(new java.awt.Color(235, 228, 228));
        jLabel13.setForeground(new java.awt.Color(13, 9, 9));
        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        /*  jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.white));
        jLabel13.setForeground(Color.black);*/
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
       jLabel13.setBackground(new java.awt.Color(123, 118, 113));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jLabel13.setForeground(new java.awt.Color(250, 250, 250));
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        loginframe.setVisible(true);
        this.dispose();
        //show  parent frame here
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel14.setForeground(Color.black);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N

        jLabel14.setForeground(new java.awt.Color(253, 251, 251));
    }//GEN-LAST:event_jLabel14MouseExited

    private void clearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllButtonActionPerformed
        // TODO add your handling code here:
        clearAll();
    }//GEN-LAST:event_clearAllButtonActionPerformed
    public void clearAll()
    {
        receiverLabel.setText("");
        phoneNoLabel.setText("");
        memberIdLabel.setText("");
        addressLabel.setText("");
        dTimeLabel.setText("");
        searchPanel.revalidate();
        searchPanel.repaint();
    }
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        clearAll();
        orderNo=searchOrderTextField.getText();
        getDetails();
        searchPanel.revalidate();
        searchPanel.repaint();
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void updateOrders()
    {   
        try {String orderNo,oTime,serviceType;
            sql="select OrderNo,OTime,ServiceType from Orders where  CookStatus='waiting' order by OTime";
            rs=stmt.executeQuery(sql);
            ordersPanel.removeAll();
            ordersPanel.revalidate();
            ordersPanel.repaint();
            ordersPanel.add(new OrderTitle());
            while(rs.next())
            {
                orderNo=rs.getString("OrderNo");
                oTime=rs.getString("OTime");                
                serviceType=rs.getString("ServiceType");                            
                ordersPanel.add(new Order(orderNo,serviceType,oTime,orderDetailsPanel,this,Ip));
                ordersPanel.revalidate();
            }
        } catch (SQLException ex) {
            System.out.println("Error, in updating orders ....");
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton clearAllButton;
    private javax.swing.JLabel dTimeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel memberIdLabel;
    private javax.swing.JPanel orderDetailsPanel;
    private javax.swing.JPanel ordersPanel;
    private javax.swing.JLabel phoneNoLabel;
    private javax.swing.JLabel receiverLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchOrderTextField;
    private javax.swing.JPanel searchPanel;
    // End of variables declaration//GEN-END:variables

    private void start() {
        
        new RefreshOrders(this);
        
       
    }

    private void setFullScreen() {
        GraphicsEnvironment environment = GraphicsEnvironment.getLocalGraphicsEnvironment();  
        GraphicsDevice device = environment.getDefaultScreenDevice();  
        device.setFullScreenWindow(this);
        
    }

    private void getConnection() {
        try {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                System.out.println("Sorry, Driver Class is not found");
            }
            con=DriverManager.getConnection("jdbc:mysql://"+Ip+":3306/LosPollosHermanos","root","8154219449");
            stmt=con.createStatement();
            s=con.createStatement();
        } catch (SQLException ex) {
            System.out.println("Error in getting the Connection");
        }
    }
}
class RefreshOrders extends Thread
{
    MainFrame mainFrame;
    RefreshOrders(MainFrame mainFrame)
    {
        this.mainFrame=mainFrame;
        start();
    }
    public void run()
    {
        for(;;)
        {
            mainFrame.updateOrders();
            try {
                Thread.sleep(10000);
            } catch (InterruptedException ex) {
                System.out.println("Interrupted Exception Occured ....");
                ex.printStackTrace();
            }
        }
    }
}
