/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lospolloshermanos;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author zubaeyr
 */
public class ShowMealDetails extends javax.swing.JPanel {
    MealItemsMaintenance MealMaint;
    String Name, Caller,sql,ImageName;
    Statement stmt;
    ResultSet result;
    int items;
    JPanel DisplayPanel;
    EmptyView empty;
    String categories[];
    /**
     * Creates new form ShowDetails
     */
    

    public ShowMealDetails(String[] categories,String Name, Statement stmt, String Caller, JPanel DisplayPanel, EmptyView empty) {
        this.categories=categories;

        this.Name=Name;
        this.Caller=Caller;
        this.DisplayPanel=DisplayPanel;
        this.empty=empty;
        this.stmt=stmt;
        initComponents(); 
        if(Caller.equals("Meals")){
            sql="Select * from Meals where MName='"+Name+"';";
        }        
        try {
            result=stmt.executeQuery(sql);
            result.next();
            ImageName=result.getString("MImage");
            if(!ImageName.equals("Empty.png")){
                            try{
                                String u=new String("C:/Program Files/RMS/images/Meals/"+ImageName);
            ImageIcon icon=new ImageIcon(new ImageIcon(u).getImage().getScaledInstance(165, 180, Image.SCALE_SMOOTH));
            jLabel1.setIcon(icon);                
            }catch(Exception e){}
            }
            else{
             ImageIcon icon=new ImageIcon(new ImageIcon(getClass().getResource("/lospolloshermanos/Empty.png")).getImage().getScaledInstance(165, 180, Image.SCALE_SMOOTH));
             jLabel1.setIcon(icon);
            }

            jLabel3.setText(Name);
            jLabel5.setText("Price : $"+result.getInt("Price"));
            jLabel9.setText("Category : "+ result.getString("CName"));
            jLabel11.setText(result.getString("Description"));
            
            jComboBox2.setSelectedItem(new String(result.getString("CName")));
        } catch (SQLException ex) {
            System.out.println("Breakpoint-1: Show Details");
        }
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Delete Category");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 247, 247), 2, true));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Delete Category");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 247, 247), 2, true));

        setBackground(new java.awt.Color(44, 44, 44));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 251, 251));
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 248, 248), 1, true));
        jLabel1.setDisabledIcon(new javax.swing.ImageIcon("/home/zubaeyr/Desktop/LosPollosHermanos/src/lospolloshermanos/Empty.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 243, 243));
        jLabel3.setText("XXXXXXXXXXX");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(244, 240, 240));
        jLabel4.setText("Price ($)");

        jLabel6.setBackground(new java.awt.Color(119, 119, 119));
        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(253, 251, 251));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Apply");
        jLabel6.setBorder(null);
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(119, 119, 119));
        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(246, 238, 238));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Close");
        jLabel10.setBorder(null);
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 243, 243));
        jLabel5.setText("Price : $XX");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(250, 243, 243));
        jLabel9.setText("Category : XXXXXXXXX");

        jLabel13.setBackground(new java.awt.Color(119, 119, 119));
        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(246, 238, 238));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Change Pic");
        jLabel13.setBorder(null);
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(250, 243, 243));
        jLabel11.setText("Spicy and Tasty!!");

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(244, 240, 240));
        jLabel14.setText("Category");

        jComboBox2.setBackground(new java.awt.Color(132, 132, 132));
        jComboBox2.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(11, 11, 11));
        jComboBox2.setMaximumRowCount(4);
        String[] categories2=new String[categories.length-1];
        for(int i=0;i<categories.length-1;i++)
        categories2[i]=categories[i+1];
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(categories2));
        jComboBox2.setAutoscrolls(true);
        jComboBox2.setBorder(null);

        jLabel16.setBackground(new java.awt.Color(119, 119, 119));
        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(246, 238, 238));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Delete");
        jLabel16.setBorder(null);
        jLabel16.setOpaque(true);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(244, 240, 240));
        jLabel17.setText("Rename");

        jLabel12.setBackground(new java.awt.Color(119, 119, 119));
        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(253, 251, 251));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Apply");
        jLabel12.setBorder(null);
        jLabel12.setOpaque(true);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(119, 119, 119));
        jLabel19.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(253, 251, 251));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Apply");
        jLabel19.setBorder(null);
        jLabel19.setOpaque(true);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19MouseExited(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(90, 90, 90));
        jTextField1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(253, 251, 251));
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(247, 237, 237));

        jTextField2.setBackground(new java.awt.Color(90, 90, 90));
        jTextField2.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(253, 251, 251));
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(247, 237, 237));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                            .addComponent(jTextField1))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addGap(1, 1, 1))
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
          jLabel10.setBackground(new java.awt.Color(235, 228, 228));
          jLabel10.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
         jLabel10.setBackground(new java.awt.Color(117, 117, 117));
        jLabel10.setForeground(new java.awt.Color(248, 244, 244));
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel6.setBackground(new java.awt.Color(235, 228, 228));
          jLabel6.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
         jLabel6.setBackground(new java.awt.Color(117, 117, 117));
        jLabel6.setForeground(new java.awt.Color(248, 244, 244));
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        jLabel13.setBackground(new java.awt.Color(235, 228, 228));
          jLabel13.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
          jLabel13.setBackground(new java.awt.Color(117, 117, 117));
        jLabel13.setForeground(new java.awt.Color(248, 244, 244));
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
           jLabel12.setBackground(new java.awt.Color(235, 228, 228));
          jLabel12.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
          jLabel12.setBackground(new java.awt.Color(117, 117, 117));
        jLabel12.setForeground(new java.awt.Color(248, 244, 244));
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel19MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseEntered
        // TODO add your handling code here:
        jLabel19.setBackground(new java.awt.Color(235, 228, 228));
          jLabel19.setForeground(new java.awt.Color(13, 9, 9));
            
    }//GEN-LAST:event_jLabel19MouseEntered

    private void jLabel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseExited
        // TODO add your handling code here:
          jLabel19.setBackground(new java.awt.Color(117, 117, 117));
        jLabel19.setForeground(new java.awt.Color(248, 244, 244));
        
    }//GEN-LAST:event_jLabel19MouseExited

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        // TODO add your handling code here:
            jLabel16.setBackground(new java.awt.Color(117, 117, 117));
        jLabel16.setForeground(new java.awt.Color(248, 244, 244));
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        // TODO add your handling code here:
         jLabel16.setBackground(new java.awt.Color(235, 228, 228));
          jLabel16.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_jLabel16MouseEntered

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
          DisplayPanel.removeAll();
              DisplayPanel.setLayout(new BorderLayout());
            DisplayPanel.add(empty);
            empty.show(true);
            DisplayPanel.revalidate();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        String ReName=jTextField1.getText();
     
        String sql="Update Meals set MName=\""+ReName.trim()+"\" where MName=\""+Name+"\";";
        try{
            stmt.executeUpdate(sql);
        }catch(Exception e){
           e.printStackTrace();
        }
        Name=ReName;
        jLabel3.setText(ReName);
        MealMaint.Update(MealMaint.sql);
        jTextField1.setText(null);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        float NewCost=Float.valueOf(jTextField2.getText().trim()).floatValue();
     
        String sql="Update Meals set Price="+NewCost+" where MName=\""+Name+"\";";
        try{
            stmt.executeUpdate(sql);
        }catch(Exception e){
           e.printStackTrace();
        }
       
        jLabel5.setText("Price : $"+NewCost);
        jTextField2.setText("");
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        String NewCategory=jComboBox2.getSelectedItem().toString().trim();     
        String sql="Update Meals set CName=\""+NewCategory+"\" where MName=\""+Name+"\";";
        try{
            stmt.executeUpdate(sql);
        }catch(Exception e){
           e.printStackTrace();
        }
     
        jLabel9.setText("Category : "+NewCategory);
        MealMaint.Update(MealMaint.sql);
        
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
         String sql="Delete From Meals Where MName='"+Name+"';";
        try{
            stmt.executeUpdate(sql);
        }catch(Exception e){
           e.printStackTrace();
        }
        MealMaint.Update(MealMaint.sql);
        DisplayPanel.removeAll();
        this.show(false);
          DisplayPanel.setLayout(new BorderLayout());
        DisplayPanel.add(empty);
        empty.show(true);
        DisplayPanel.revalidate();
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        FileChooser fchose=new FileChooser(this);
        fchose.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked
public void Updatepic(String location,String FileName){
  
      	String finalloc="C:/Program Files/RMS/images/Meals/"+FileName.trim();
	File file=new File(location);
	InputStream in;
	try {
            in = new FileInputStream(file);
            OutputStream out = new FileOutputStream(finalloc);
	    byte[] buf = new byte[1024];        
	    int len = 0;
	    while ((len = in.read(buf)) != -1) {
	        out.write(buf, 0, len);
	    }
	    out.flush();
	    out.close();
	} catch (Exception e) {
            e.printStackTrace();
	}   

        if(!ImageName.equals("Empty.png")){
            File f=new File("C:/Program Files/RMS/images/Meals/"+ImageName);
            f.delete();
        }
        ImageName=FileName.trim();
        String sql="Update Meals set MImage=\""+FileName.trim()+"\" where MName=\""+Name+"\";";
        try{
            stmt.executeUpdate(sql);
        }catch(Exception e){
           e.printStackTrace();
        }
    
      
        try {
            String u=new String("C:/Program Files/RMS/images/Meals/"+FileName);
          ImageIcon icon=new ImageIcon(new ImageIcon(u).getImage().getScaledInstance(165, 180, Image.SCALE_SMOOTH));
            jLabel1.setIcon(icon);
            MealMaint.Update(MealMaint.sql);
        } catch (Exception ex) {
            Logger.getLogger(ShowDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
