/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lospolloshermanos;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author zubaeyr
 */
public class ShowDetails extends javax.swing.JPanel {

    /**
     * Creates new form ShowDetails
     */
    String Name, Caller,sql,ImageName;
    Statement stmt;
    ResultSet result;
    int items;
    JPanel DisplayPanel;
    EmptyView empty;
    CategoryMaintenance catMaint;
    MealItemsMaintenance MealMaint;
    public ShowDetails(String Name, Statement stmt,String caller,JPanel DisplayPanel, EmptyView empty,MealItemsMaintenance MealMaint) {
        initComponents();
        this.Name=Name;
        this.Caller=caller;
        this.DisplayPanel=DisplayPanel;
        this.empty=empty;
        this.stmt=stmt;
        this.MealMaint=MealMaint;
        if(caller.equals("Category")){
            sql="Select CImage from MealCategory where CName='"+Name+"';";
        }        
        try {
            result=stmt.executeQuery(sql);
            result.next();
            ImageName=result.getString("CImage");
            sql="Select MName from Meals where CName='"+Name+"'";
            result=stmt.executeQuery(sql);
            result.last();
            items=result.getRow();            
        } catch (SQLException ex) {
            System.out.println("Breakpoint-1: Show Details");
        }
        if(!ImageName.equals("Empty.png")){
        try{
            ImageIcon icon=new ImageIcon(new ImageIcon("C:/Program Files/RMS/images/Category/"+ImageName).getImage().getScaledInstance(189, 239, Image.SCALE_SMOOTH));
            jLabel1.setIcon(icon);   
        }catch(Exception e){}
        }
        else{
         ImageIcon icon=new ImageIcon(new ImageIcon(getClass().getResource("/lospolloshermanos/Empty.png")).getImage().getScaledInstance(189, 239, Image.SCALE_SMOOTH));   
        jLabel1.setIcon(icon);
        }
        
        jLabel3.setText(Name);
        jLabel5.setText("No. of Types : "+items);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Delete Category");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 247, 247), 2, true));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Delete Category");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(254, 247, 247), 2, true));

        setBackground(new java.awt.Color(50, 50, 50));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(207, 207, 207)));
        setMaximumSize(new java.awt.Dimension(400, 435));
        setMinimumSize(new java.awt.Dimension(400, 435));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 251, 251));
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 248, 248), 1, true));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 243, 243));
        jLabel3.setText("XXXXXXXXX");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(244, 240, 240));
        jLabel4.setText("Rename");

        jLabel6.setBackground(new java.awt.Color(119, 119, 119));
        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(253, 251, 251));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Apply");
        jLabel6.setBorder(null);
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(119, 119, 119));
        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 17)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(246, 238, 238));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Close");
        jLabel10.setBorder(null);
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 243, 243));
        jLabel5.setText("No. Of Types : 0");

        jLabel12.setBackground(new java.awt.Color(117, 117, 117));
        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(248, 244, 244));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Change Pic");
        jLabel12.setBorder(null);
        jLabel12.setOpaque(true);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPane4.setBackground(new java.awt.Color(52, 52, 52));
        jTextPane4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jTextPane4.setForeground(new java.awt.Color(252, 245, 245));
        jTextPane4.setCaretColor(new java.awt.Color(251, 249, 249));
        jScrollPane4.setViewportView(jTextPane4);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(250, 243, 243));
        jLabel9.setText("Yummy and Tasty!");

        jLabel13.setBackground(new java.awt.Color(119, 119, 119));
        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(246, 238, 238));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Delete Category");
        jLabel13.setBorder(null);
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
        jLabel12.setBackground(new java.awt.Color(235, 228, 228));
          jLabel12.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
        jLabel12.setBackground(new java.awt.Color(117, 117, 117));
        jLabel12.setForeground(new java.awt.Color(248, 244, 244));

    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
          jLabel10.setBackground(new java.awt.Color(235, 228, 228));
          jLabel10.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
         jLabel10.setBackground(new java.awt.Color(117, 117, 117));
        jLabel10.setForeground(new java.awt.Color(248, 244, 244));
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        jLabel6.setBackground(new java.awt.Color(235, 228, 228));
          jLabel6.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
         jLabel6.setBackground(new java.awt.Color(117, 117, 117));
        jLabel6.setForeground(new java.awt.Color(248, 244, 244));
        
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        jLabel13.setBackground(new java.awt.Color(235, 228, 228));
          jLabel13.setForeground(new java.awt.Color(13, 9, 9));
      
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
          jLabel13.setBackground(new java.awt.Color(117, 117, 117));
        jLabel13.setForeground(new java.awt.Color(248, 244, 244));
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        DisplayPanel.removeAll();
        DisplayPanel.setLayout(new BorderLayout());
        this.show(false);
            
            DisplayPanel.add(empty);
            empty.show(true);
            DisplayPanel.revalidate();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        String ReName=jTextPane4.getText();
     
        String sql="Update MealCategory set CName=\""+ReName.trim()+"\" where CName=\""+Name+"\";";
        String sql2="Update Meals set CName='"+ReName.trim()+"' where CName='"+Name+"';";
        try{
            stmt.executeUpdate(sql);
            stmt.executeUpdate(sql2);
        }catch(Exception e){
           e.printStackTrace();
        }
        Name=ReName;
        jLabel3.setText(ReName);
        catMaint.Update();
        jTextPane4.setText(null);
        
        MealMaint.Updatecategories();
        MealMaint.ComboBoxUpdate();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        String sql="Delete From MealCategory Where CName='"+Name+"';";
        String sql2="Delete From Meals Where CName='"+Name+"';";
        try{
            stmt.executeUpdate(sql);
            stmt.executeUpdate(sql2);
        }catch(Exception e){
           e.printStackTrace();
        }
        catMaint.Update();
        DisplayPanel.removeAll();
         DisplayPanel.setLayout(new BorderLayout());
        DisplayPanel.add(empty);
        empty.show(true);
       DisplayPanel.revalidate();
        MealMaint.Updatecategories();
        MealMaint.ComboBoxUpdate();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        
        FileChooser fchose=new FileChooser(this);
        fchose.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked
    public void Updatepic(String location,String FileName){
      
      	String finalloc="C:/Program Files/RMS/images/Category/"+FileName.trim();
	File file=new File(location);
	InputStream in;
	try {
            in = new FileInputStream(file);
            OutputStream out = new FileOutputStream(finalloc);
	    byte[] buf = new byte[1024];        
	    int len = 0;
	    while ((len = in.read(buf)) != -1) {
	        out.write(buf, 0, len);
	    }
	    out.flush();
	    out.close();
	} catch (Exception e) {
            e.printStackTrace();
	}   

        if(!ImageName.equals("Empty.png")){
            File f=new File("C:/Program Files/RMS/images/Category/"+ImageName);
            f.delete();
        }
        ImageName=FileName.trim();
        String sql="Update MealCategory set CImage=\""+FileName.trim()+"\" where CName=\""+Name+"\";";
        try{
            stmt.executeUpdate(sql);
        }catch(Exception e){
           e.printStackTrace();
        }
    
      
        try {
            String u=new String("C:/Program Files/RMS/images/Category/"+FileName);
          ImageIcon icon=new ImageIcon(new ImageIcon(u).getImage().getScaledInstance(189, 239, Image.SCALE_SMOOTH));
            jLabel1.setIcon(icon);
            catMaint.Update();
        } catch (Exception ex) {
            Logger.getLogger(ShowDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane4;
    // End of variables declaration//GEN-END:variables
}
