/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lospolloshermanos;

import java.awt.Image;
import java.io.File;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author zubaeyr
 */
public class StaffLabels extends javax.swing.JPanel {

    String Name,UserID,Position,Status;
    Statement stmt;
    JPanel DisplayPanel;
    StaffMaintenance staffmaint;
    EmptyView empty;
    //private String javaapplication1;
    /**
     * Creates new form Item
     */
    public StaffLabels(String UserName,String Name,String Position, String Status,Statement stmt,StaffMaintenance staffmaint,EmptyView empty,JPanel DisplayPanel) { 
       this.Name=Name;
       this.UserID=UserName;
       this.Position=Position;
       this.Status=Status;
       this.stmt=stmt;
       this.DisplayPanel=DisplayPanel;
       this.staffmaint=staffmaint;
       this.empty=empty;
       initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(17, 13, 13));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(215, 208, 208)));
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(619, 30));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(87, 78, 78));
        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 234, 234));
        jLabel2.setText("Name ");
        jLabel2.setBorder(null);
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel2.setPreferredSize(null);
        jLabel2.setText(Name);

        jLabel3.setBackground(new java.awt.Color(87, 78, 78));
        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 234, 234));
        jLabel3.setText("User ID");
        jLabel3.setBorder(null);
        jLabel3.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel3.setPreferredSize(null);
        jLabel3.setText(UserID);

        jLabel4.setBackground(new java.awt.Color(87, 78, 78));
        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 234, 234));
        jLabel4.setText("Position");
        jLabel4.setBorder(null);
        jLabel4.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel4.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel4.setPreferredSize(null);
        jLabel4.setText(Position);

        jLabel5.setBackground(new java.awt.Color(87, 78, 78));
        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(241, 234, 234));
        jLabel5.setText("Status");
        jLabel5.setBorder(null);
        jLabel5.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel5.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel5.setPreferredSize(null);
        jLabel5.setText(Status);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
          //  setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 236, 236)));
            //this.setBackground(new java.awt.Color(235, 228, 228));
            setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
            jLabel2.setForeground(new java.awt.Color(13, 9, 9));
            jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
            jLabel3.setForeground(new java.awt.Color(13, 9, 9));
            jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
            jLabel4.setForeground(new java.awt.Color(13, 9, 9));
            jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
            jLabel5.setForeground(new java.awt.Color(13, 9, 9));
            jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
            
         
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
         this.setBackground(new java.awt.Color(17, 13, 13));
         jLabel2.setForeground(new java.awt.Color(241, 234, 234));
         jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 11)); // NOI18N
         jLabel3.setForeground(new java.awt.Color(241, 234, 234));
         jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 11));
         jLabel4.setForeground(new java.awt.Color(241, 234, 234));
         jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 11));
         jLabel5.setForeground(new java.awt.Color(241, 234, 234));
         jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 11));

    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        new ShowEmployee(UserID,stmt,DisplayPanel,empty,staffmaint);

    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
