/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lospolloshermanos;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author zubaeyr
 */
public class FileChooser extends javax.swing.JFrame {

    /**
     * Creates new form FileChooser
     */
              ShowDetails showd;
             CategoryMaintenance catMaint;
             ShowMealDetails showmd;
             MealItemsMaintenance MealMaint;
             AddNewStaff AddStaff;
             ShowEmployee ShowEmp;
    public FileChooser(ShowDetails showd) {
     
        initComponents();
        this.showd=showd;
        this.setLocationRelativeTo(null);    
    }
     public FileChooser(CategoryMaintenance catMaint) {
        initComponents();
        this.catMaint=catMaint;
        this.setLocationRelativeTo(null);    
    }
     public FileChooser(ShowMealDetails showmd) {
     
        initComponents();
        this.showmd=showmd;
        this.setLocationRelativeTo(null);    
    }
      public FileChooser(MealItemsMaintenance MealItems) {
     
        initComponents();
        this.MealMaint=MealItems;
        this.setLocationRelativeTo(null);    
    }
      public FileChooser(AddNewStaff AddStaff){
          initComponents();
          this.AddStaff=AddStaff;
          this.setLocationRelativeTo(null);
          
      }
    public FileChooser(ShowEmployee ShowEmp){
          initComponents();
          this.ShowEmp=ShowEmp;
          this.setLocationRelativeTo(null);
          
      }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(80, 80, 80));
        setUndecorated(true);
	try{
	        setOpacity(0.95F);
	}catch(Exception e){}
        setResizable(false);

        jFileChooser1.setApproveButtonText("Choose");
        jFileChooser1.setBackground(new java.awt.Color(95, 95, 95));
        jFileChooser1.setDialogTitle("");
        jFileChooser1.setForeground(new java.awt.Color(234, 225, 225));
        jFileChooser1.setDoubleBuffered(true);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        this.hide();
 
        if(showd!=null){
            if (evt.getActionCommand().equals("ApproveSelection")) {
                File selectedFile = jFileChooser1.getSelectedFile();
                showd.Updatepic(selectedFile.getPath().trim(),selectedFile.getName());
            }    
        }
        else if(catMaint!=null){
             if (evt.getActionCommand().equals("ApproveSelection")) {
                File selectedFile = jFileChooser1.getSelectedFile();
                catMaint.location=selectedFile.getPath().trim();
                catMaint.NewCatName=selectedFile.getName().trim();
             }
        }
        else if(showmd!=null){
            if (evt.getActionCommand().equals("ApproveSelection")) {
                File selectedFile = jFileChooser1.getSelectedFile();
                showmd.Updatepic(selectedFile.getPath().trim(),selectedFile.getName());
            }   
        }
        else if(MealMaint!=null){
             if (evt.getActionCommand().equals("ApproveSelection")) {
                File selectedFile = jFileChooser1.getSelectedFile();
                MealMaint.location=selectedFile.getPath().trim();
                MealMaint.NewMealName=selectedFile.getName().trim();
             }
        }
        else if(AddStaff!=null){
             if (evt.getActionCommand().equals("ApproveSelection")) {
                File selectedFile = jFileChooser1.getSelectedFile();
                AddStaff.ImgLocation=selectedFile.getPath().trim();
                AddStaff.NewImgName=selectedFile.getName().trim();
             }
        }
        else if(ShowEmp!=null){
            if (evt.getActionCommand().equals("ApproveSelection")) {
                File selectedFile = jFileChooser1.getSelectedFile();
                ShowEmp.Updatepic(selectedFile.getPath().trim(),selectedFile.getName());
            }  
        }
        this.dispose();
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
