/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lospolloshermanos;

import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author zubaeyr
 */
public class Item extends javax.swing.JPanel {

    String name,iconName, Name,Caller;
    ImageIcon icon;
    JPanel DisplayPanel;
    Statement stmt;
    EmptyView empty;
    CategoryMaintenance catMaint;
    MealItemsMaintenance mealItems;
    String[] categories;
    MealItemsMaintenance MealcalledfromCat;
    //private String javaapplication1;
    /**
     * Creates new form Item
     */
    public Item(String iconName,String name,String Caller,JPanel DisplayPanel,Statement stmt,EmptyView empty) {
        this.Caller=Caller;
        this.DisplayPanel=DisplayPanel;
        this.stmt=stmt;
        this.name=name;
        this.iconName=iconName;
        this.empty=empty;
        
        if(iconName.equals("black.png")){
      
                 icon=new ImageIcon(new ImageIcon(getClass().getResource("/lospolloshermanos/black.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
            
        }
        else if(Caller.equals("Category")){
           if(iconName.equals("Empty.png")){
                    icon=new ImageIcon(new ImageIcon(getClass().getResource("/lospolloshermanos/Empty.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
           }else{

                String u=new String("/home/zubaeyr/Pictures/images/Category/"+iconName);
                 icon=new ImageIcon(new ImageIcon(u).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
           }
        }
        else if(Caller.equals("Meals")){
           if(iconName.equals("Empty.png")){
                    icon=new ImageIcon(new ImageIcon(getClass().getResource("/lospolloshermanos/Empty.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
           }else{

           
                String u1=new String("/home/zubaeyr/Pictures/images/Meals/"+iconName);
                 icon=new ImageIcon(new ImageIcon(u1).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
           }
        }
        initComponents();
        jLabel3.show(false);
    }
    String TableNo,TableSize;
    
    int click=0;
    public Item(String ImgName,String TableNo, String TableSize){
        this.TableNo=TableNo;
        this.TableSize=TableSize;
        this.iconName=ImgName;
        
        if(!iconName.equals("black.png")){
               icon=new ImageIcon(new ImageIcon(getClass().getResource("/lospolloshermanos/tables3.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
              
        }
        else{
             icon=new ImageIcon(new ImageIcon(getClass().getResource("/lospolloshermanos/black.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));            
        }
        initComponents();
        jLabel3.show(false);
        if(!iconName.equals("black.png")){
             jLabel2.setText("Table No : "+TableNo);
             jLabel3.setText("Capacity : "+TableSize);
            jLabel3.show(true);
        }
        Caller="Tables";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(17, 13, 13));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jLabel1.setIcon(icon);
        jLabel1.setBackground(new java.awt.Color(17, 13, 13));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(87, 78, 78));
        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 234, 234));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("XXXX");
        jLabel2.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel2.setText(name);

        jLabel3.setBackground(new java.awt.Color(87, 78, 78));
        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 234, 234));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("XXXX");
        jLabel3.setMaximumSize(new java.awt.Dimension(50, 20));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 20));
        jLabel2.setText(name);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
        if(!iconName.equals("black.png")){
            setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 236, 236)));
            //this.setBackground(new java.awt.Color(235, 228, 228));
               setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
            jLabel2.setForeground(new java.awt.Color(13, 9, 9));
            jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 16));
        }
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        if(!iconName.equals("black.png")){
        setBorder(null);
        this.setBackground(new java.awt.Color(17, 13, 13));
        jLabel2.setForeground(new java.awt.Color(241, 234, 234));
         jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
         if(click==1){
               setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
         }
        }

    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if(Caller.equals("Category")&&!iconName.equals("black.png")){
            DisplayPanel.removeAll();
             DisplayPanel.setLayout(new BorderLayout());
            ShowDetails showp=new ShowDetails(name, stmt,Caller,DisplayPanel, empty,MealcalledfromCat);
            showp.catMaint=this.catMaint;
            showp.show(true);
            DisplayPanel.add(showp);
            DisplayPanel.revalidate();
        }
        else if(Caller.equals("Meals")&&!iconName.equals("black.png")){
            DisplayPanel.removeAll();
                 DisplayPanel.setLayout(new BorderLayout());
            ShowMealDetails showm=new ShowMealDetails(categories,name, stmt,Caller,DisplayPanel, empty);
            showm.MealMaint=this.mealItems;

            showm.show(true);
            DisplayPanel.add(showm);
            DisplayPanel.revalidate();
        }
        if(TableNo!=null && click==0 &&!iconName.equals("black.png")){
           
            setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
            click=1;
        }
        else if(click==1){
           
             this.setBackground(new java.awt.Color(17, 13, 13));
             click=0;
        }
        
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
