/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lospolloshermanos;

import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author zubaeyr
 */
public class ShowEmployee extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployee
     */
    Statement stmt;
    JPanel DisplayPanel;
    EmptyView empty;
    StaffMaintenance staffmaint;
    String OriginalUserName;
    ResultSet result;
    String ImageName;
    public ShowEmployee(String OriginalUserName,Statement stmt, JPanel DisplayPanel,EmptyView empty,StaffMaintenance staffmaint) {
        this.stmt=stmt;
        this.staffmaint=staffmaint;
        this.DisplayPanel=DisplayPanel;
        this.OriginalUserName=OriginalUserName;
        this.empty=empty;
        initComponents();
        Load();
        DisplayPanel.removeAll();
        this.show(false);
          DisplayPanel.setLayout(new BorderLayout());
        DisplayPanel.add(this);
        this.show(true);
        DisplayPanel.revalidate();
    }
    public void Load(){
        try {
           
            String sql="select * from StaffDetails where username='"+OriginalUserName+"';";
            result=stmt.executeQuery(sql);
            result.next();
            jTextField1.setText(result.getString("fullname"));
            jTextField3.setText(result.getString("username"));
            jTextField2.setText(result.getString("email"));
            jTextField4.setText(result.getString("phone"));
            jTextField5.setText(result.getString("password"));
            jTextPane1.setText(result.getString("address"));
            jTextField6.setText(result.getString("salary"));
            ImageName=result.getString("SImage");
            jComboBox1.setSelectedItem(new String(result.getString("position")));
            jComboBox2.setSelectedItem(new String(result.getString("status")));
        } catch (SQLException ex) {
            Logger.getLogger(ShowEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }

           if(!ImageName.equals("Empty.png")){
                            try{
                                String u=new String("/home/zubaeyr/Pictures/images/Staff/"+ImageName);
            ImageIcon icon=new ImageIcon(new ImageIcon(u).getImage().getScaledInstance(109 , 107, Image.SCALE_SMOOTH));
            jLabel13.setIcon(icon);                
            }catch(Exception e){}
            }
            else{
             ImageIcon icon=new ImageIcon(new ImageIcon(getClass().getResource("/lospolloshermanos/Empty.png")).getImage().getScaledInstance(109, 107, Image.SCALE_SMOOTH));
             jLabel13.setIcon(icon);
            }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(23, 23, 23));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));

        jLabel10.setBackground(new java.awt.Color(119, 119, 119));
        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(246, 238, 238));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Close");
        jLabel10.setBorder(null);
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(119, 119, 119));
        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(246, 238, 238));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Save");
        jLabel11.setBorder(null);
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });

        jTextPane1.setBackground(new java.awt.Color(92, 90, 90));
        jTextPane1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(241, 234, 234));
        jScrollPane1.setViewportView(jTextPane1);

        jTextField4.setBackground(new java.awt.Color(83, 83, 83));
        jTextField4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(241, 234, 234));
        jTextField4.setBorder(null);
        jTextField4.setCaretColor(new java.awt.Color(245, 235, 235));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(253, 243, 243));
        jLabel6.setText("Phone No.");

        jTextField2.setBackground(new java.awt.Color(83, 83, 83));
        jTextField2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(241, 234, 234));
        jTextField2.setBorder(null);
        jTextField2.setCaretColor(new java.awt.Color(245, 235, 235));

        jLabel5.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(253, 243, 243));
        jLabel5.setText("Email ID");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(253, 243, 243));
        jLabel3.setText("Password");

        jTextField3.setBackground(new java.awt.Color(83, 83, 83));
        jTextField3.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(241, 234, 234));
        jTextField3.setBorder(null);
        jTextField3.setCaretColor(new java.awt.Color(245, 235, 235));

        jLabel4.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(253, 243, 243));
        jLabel4.setText("User Name");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(253, 243, 243));
        jLabel2.setText("Full Name");

        jTextField1.setBackground(new java.awt.Color(83, 83, 83));
        jTextField1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(241, 234, 234));
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(245, 235, 235));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 243, 243));
        jLabel1.setText("Register As");

        jComboBox1.setBackground(new java.awt.Color(135, 132, 132));
        jComboBox1.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(16, 14, 14));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Staff", "Chef", "Manager" }));
        jComboBox1.setBorder(null);

        jLabel8.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(250, 243, 243));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Employee Detials");

        jTextField5.setBackground(new java.awt.Color(83, 83, 83));
        jTextField5.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(241, 234, 234));
        jTextField5.setBorder(null);
        jTextField5.setCaretColor(new java.awt.Color(245, 235, 235));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(253, 243, 243));
        jLabel7.setText("Address");

        jLabel12.setBackground(new java.awt.Color(119, 119, 119));
        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(246, 238, 238));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Delete");
        jLabel12.setBorder(null);
        jLabel12.setOpaque(true);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(253, 243, 243));
        jLabel9.setText("Status");

        jComboBox2.setBackground(new java.awt.Color(135, 132, 132));
        jComboBox2.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(16, 14, 14));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "In-Active" }));
        jComboBox2.setBorder(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lospolloshermanos/Empty.png"))); // NOI18N

        jLabel14.setBackground(new java.awt.Color(119, 119, 119));
        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(246, 238, 238));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Change Pic");
        jLabel14.setBorder(null);
        jLabel14.setOpaque(true);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(83, 83, 83));
        jTextField6.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(241, 234, 234));
        jTextField6.setBorder(null);
        jTextField6.setCaretColor(new java.awt.Color(245, 235, 235));

        jLabel15.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(253, 243, 243));
        jLabel15.setText("Salary($)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(227, 227, 227))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(227, 227, 227))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField6)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(201, 201, 201))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        DisplayPanel.removeAll();
        this.show(false);
         DisplayPanel.setLayout(new BorderLayout());
        DisplayPanel.add(empty);
        empty.show(true);
        DisplayPanel.revalidate();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        jLabel10.setBackground(new java.awt.Color(235, 228, 228));
        jLabel10.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
        jLabel10.setBackground(new java.awt.Color(117, 117, 117));
        jLabel10.setForeground(new java.awt.Color(248, 244, 244));
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        int i=0;
        String Name=jTextField1.getText().trim();
        String UserName=jTextField3.getText().trim();
        String Password=jTextField5.getText().trim();
        String Email=jTextField2.getText().trim();
        String Phone=jTextField4.getText().trim();
        String Position=jComboBox1.getSelectedItem().toString();
        String Address=jTextPane1.getText();
        String Status=jComboBox2.getSelectedItem().toString();
        String Salary=jTextField6.getText();
        String sql="update StaffDetails set username='"+UserName+"',password='"+Password+"',fullname='"+Name+"',position='"+Position+"',email='"+Email+"',phone='"+Phone+"',address='"+Address+"',status='"+Status+"',salary='"+Salary+"' where username='"+OriginalUserName+"';";
        try {
            if(Name.equals("")||UserName.equals("")||Password.equals("")||Email.equals("")||Phone.equals("")||Position.equals("")||Address.equals("")){
                throw new NullPointerException();
            }
            
            stmt.executeUpdate(sql);
            System.out.println("Here");
        }catch(NullPointerException e){
            //do nothing
            new ErrorDialog(2);
        }catch(Exception e){
            new ErrorDialog(1);
           i=1;
            jTextField3.setText("");
        }
        staffmaint.Update(staffmaint.sql);
        if(i==0){
            OriginalUserName=UserName;
            i=0;
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
        jLabel11.setBackground(new java.awt.Color(235, 228, 228));
        jLabel11.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
        jLabel11.setBackground(new java.awt.Color(117, 117, 117));
        jLabel11.setForeground(new java.awt.Color(248, 244, 244));
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
       String sql="delete from StaffDetails where username='"+OriginalUserName+"';";
        try {
            stmt.executeUpdate(sql);
        }catch(Exception e){  
        }
        DisplayPanel.removeAll();
        this.show(false);
         DisplayPanel.setLayout(new BorderLayout());
         DisplayPanel.add(empty);
        staffmaint.Update(staffmaint.sql);
        DisplayPanel.revalidate();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        // TODO add your handling code here:
          jLabel12.setBackground(new java.awt.Color(235, 228, 228));
        jLabel12.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
           jLabel12.setBackground(new java.awt.Color(117, 117, 117));
        jLabel12.setForeground(new java.awt.Color(248, 244, 244));
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        FileChooser fchose=new FileChooser(this);
        fchose.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
          jLabel14.setBackground(new java.awt.Color(235, 228, 228));
        jLabel14.setForeground(new java.awt.Color(13, 9, 9));
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
        jLabel14.setBackground(new java.awt.Color(117, 117, 117));
        jLabel14.setForeground(new java.awt.Color(248, 244, 244));
    }//GEN-LAST:event_jLabel14MouseExited
public void Updatepic(String location,String FileName){
  
      	String finalloc="/home/zubaeyr/Pictures/images/Staff/"+FileName.trim();
	File file=new File(location);
	InputStream in;
	try {
            in = new FileInputStream(file);
            OutputStream out = new FileOutputStream(finalloc);
	    byte[] buf = new byte[1024];        
	    int len = 0;
	    while ((len = in.read(buf)) != -1) {
	        out.write(buf, 0, len);
	    }
	    out.flush();
	    out.close();
	} catch (Exception e) {
            e.printStackTrace();
	}   

        if(!ImageName.equals("Empty.png")){
            File f=new File("/home/zubaeyr/Pictures/images/Staff/"+ImageName);
            f.delete();
        }
        ImageName=FileName.trim();
        String sql="Update StaffDetails set SImage=\""+FileName.trim()+"\" where username=\""+OriginalUserName+"\";";
        try{
            stmt.executeUpdate(sql);
        }catch(Exception e){
           e.printStackTrace();
        }
    
      
        try {
            String u=new String("/home/zubaeyr/Pictures/images/Staff/"+FileName);
          ImageIcon icon=new ImageIcon(new ImageIcon(u).getImage().getScaledInstance(109, 107, Image.SCALE_SMOOTH));
            jLabel13.setIcon(icon);
        } catch (Exception ex) {
            Logger.getLogger(ShowDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
