/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OrderAndReservation;

import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author zubaeyr
 */
public class Items extends javax.swing.JPanel {

    String ItemName,IconName;
    ImageIcon icon;
    JPanel DisplayPanel;
    Statement statement;
    OrderingSystem orderingpan;
    EmptyView empty;
    CartPanel cart;
    //private String javaapplication1;
    /**
     * Creates new form Item
     */
    public Items(String IconName,String ItemName,JPanel DisplayPanel,Statement statement,EmptyView empty,CartPanel cart) {        
        this.cart=cart;
        this.DisplayPanel=DisplayPanel;
        this.statement=statement;
        this.ItemName=ItemName;
        this.IconName=IconName;
        this.empty=empty;
        if(IconName.equals("black.png")){
                 icon=new ImageIcon(new ImageIcon(getClass().getResource("/OrderAndReservation/black.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
            
        }
        if(IconName.equals("Empty.png")){
                    icon=new ImageIcon(new ImageIcon(getClass().getResource("/OrderAndReservation/Empty.png")).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
        }else{
          try {
              String u=new String("C:/Program Files/RMS/images/Meals/"+IconName);
                icon=new ImageIcon(new ImageIcon(u).getImage().getScaledInstance(140, 140, Image.SCALE_SMOOTH));
            } catch (Exception ex) {
              System.out.println("Breaking point 1: item2");
            }
           }
        
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(17, 13, 13));
        setBorder(null);
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        ImageLabel.setIcon(icon);
        ImageLabel.setBackground(new java.awt.Color(17, 13, 13));
        ImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        NameLabel.setBackground(new java.awt.Color(87, 78, 78));
        NameLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(241, 234, 234));
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameLabel.setText("XXXX");
        NameLabel.setMaximumSize(new java.awt.Dimension(50, 20));
        NameLabel.setMinimumSize(new java.awt.Dimension(50, 20));
        NameLabel.setText(ItemName);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(ImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered

        if(!IconName.equals("black.png")){
            setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(244, 236, 236)));
            setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
            NameLabel.setForeground(new java.awt.Color(13, 9, 9));
            NameLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 16));
        }
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited

        if(!IconName.equals("black.png")){
        setBorder(null);
        this.setBackground(new java.awt.Color(17, 13, 13));
        NameLabel.setForeground(new java.awt.Color(241, 234, 234));
        NameLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13));
        }

    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked


        if(!IconName.equals("black.png")){
            DisplayPanel.removeAll();
            DisplayPanel.setLayout(new BorderLayout());
            ShowMealDetails showmealdetails=new ShowMealDetails(ItemName, statement,DisplayPanel, empty,cart);
            showmealdetails.orderingpan=this.orderingpan;
            showmealdetails.show(true);
            DisplayPanel.add(showmealdetails);
           DisplayPanel.revalidate();
            orderingpan.revalidate();
        }        
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JLabel NameLabel;
    // End of variables declaration//GEN-END:variables
}
